### ISSUE TITLE
Get All Product

### ISSUE THREAD

**Issue by Firmnsyaah** [blueharvest-alterra/go-back-end#88]
Get all product with invalid endpoint
expected 404 actual 500
![image](https://github.com/blueharvest-alterra/go-back-end/assets/160707722/e2fc5761-4267-4d39-98f4-e674a779e62b)
![image](https://github.com/blueharvest-alterra/go-back-end/assets/160707722/08ac9c2d-fe32-435c-87f1-1630be6d9d14)

**Comment by IrvanSN** [comment]
halo mas, untuk endpoint GetAllProducts hanya di /v1/products aja yaa. kalau sudah masuk ke /v1/products/invalid jatuhnya ke endpoint GetByProductID.
